project:
  type: website
  output-dir: docs

website:
  title: "SisengAI"
  site-url: "https://SisengAI.com"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd # my new Navigation Bar
        text: Resources
      - href: blog_posts.qmd # add your blog_posts.qmd file to the navbar of your website!
        text: SisengAI Blog

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true
editor: visual