project:
  type: website
  output-dir: docs

website:
  title: "SisengAI"
  site-url: "https://SisengAI.com"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      
      - href: blog_posts.qmd # add your blog_posts.qmd file to the navbar of your website!
        text: SisengAI Blog
  page-footer: 
    #background: light
    left: 
      - "Copyright © 2023, SisengAI"
    right: 
      - icon: github
        href: https://github.com/theAfricanQuant
      - icon: twitter
        href: https://twitter.com/theAfricanQuant
  reader-mode: true

format:
  html: 
    page-layout: full
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true
editor: visual