project:
  type: website
  output-dir: docs

website:
  title: "SisengAI"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resources.qmd # my new Navigation Bar
        text: Resources
    right: 
      - blog_posts.qmd # add your blog_posts.qmd file to the navbar of your website!

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true
editor: visual